const mongoose = require("mongoose");

const UserSchema = new mongoose.Schema({
  id: { type: String, required: true },
  balance: { type: Number, default: 0 },
  xp: { type: Number, default: 100 },
  level: { type: Number, default: 1 },
  selected: { type: Number, default: 0 },
  pokemons: { type: Array, default: [] },
  redeems: { type: Number, default: 0 },
  satyamOP : { type: Boolean, default: false },
  badges: { type: Array, default: [] },
  orderAlphabet: { type: Boolean, default: false },
  orderIV: { type: Boolean, default: false },
  orderLevel: { type: Boolean, default: false },
  streak: { type: Number, default: 0 },
  shards: { type: Number, default: 0 },
  redeems: {type: Number, default: 0 },
  shinyCaught: {type: Number, default: 0 },
  caught: {type: Array, default: [] },
  released: {type: Number, default: 0},
  blacklist: { type: Boolean, default: false },
  creation: {type: String, default: Date.now()},
  lbcaught: {type:Number, default: 0},
  pbcrates: {type:Number, default: 0},
  shcrate: {type:Number, default: 0},
  ubcrates: {type:Number, default: 0},
  mbcrates: {type:Number, default: 0},
  cool: { type: Boolean, default: 0},
  egg: {type:Number, default: 3},
  upvotes: { type: Boolean, default: 0},
  pb: {type:Number, default: 0},
  pbs: {type:Number, default: 0},
  code: {type:Number, default: 0},
  summon: {type:Number, default: 0},
  questcaught:{type:Number, default: 0},
  shcount: {type:Number, default: 0},
  questcaught: {type:Number, default: 0},
  questclaim: {type:Number, default: 0},
  questclaim2: {type:Number, default: 0},
   questclaim3: {type:Number, default: 0},
  shname: {type:String, default: null}
});

module.exports = mongoose.model("User", UserSchema);
